### ISSUE TITLE
How to install on version 9.5

### ISSUE THREAD

**Issue by zloi47** [eulerto/pg_similarity#11]
when running "make" in builds in directory for 9.4, what should I change to force it install on postgres 9.5?

**Comment by eulerto** [comment]
Is postgres 9.5 in your PATH?

$ echo $PATH
$ export PATH=/home/foo/pg951/bin:$PATH
$ USE_PGXS=1 make

If it does not work, show me the commands.

**Comment by zloi47** [comment]
I am somehow new to ubuntu actually, but when searching for pg_config in ubuntu, it shows only:

/usr/lib/postgresql/9.4/bin/pg_config
/usr/bin/pg_config

**Comment by zloi47** [comment]
I installed posgresql-server-dev-9.5,  but now it shows:

```
postgres=# create extension pg_similarity;
ERROR:  incompatible library "/usr/lib/postgresql/9.5/lib/pg_similarity.so": version mismatch
DETAIL:  Server is version 9.5, library is version 9.4.
```

**Comment by eulerto** [comment]
PGS_MAX_STR_LEN at similarity.h
