### ISSUE TITLE
Problema na Instalação do PG_SIMILARITY

### ISSUE THREAD

**Issue by gustavomarcon** [eulerto/pg_similarity#7]
Euler, estou tendo problemas para instalar o pg_similarity no meu Ubuntu sobre uma VM. O problema ocorre a partir da linha do Makefile. Gostaria de saber se você tem algum outro 'how to install' atualizado ou se você sabe os pontos principais que devem ser atualizados no Makefile.

Obrigado.

**Comment by eduardoriveror** [comment]
Bom dia

eu estou tendo problemas para instalar pg_similarity on postgresql 9.3, quando eu faco make install instala no diretorio /etc/postgresql/9.6/main mas eu tenho 9.3. Quando uso create extension pg_similarity o servidor responde "could not open extension control file "/usr/share/postgresql/9.3/extension/pg_similarity.control": No such file or directory" Voce tem una versao mas atual do "how to install"

**Comment by eulerto** [comment]
@eduardoriveror você poderia ter aberto outro "issue". Informe os passos para instalação. Além disso, qual é a saída de:

pg_config --version
pg_config --libdir

Após instalar, o arquivo pg_similarity.so está no diretório apontado pelo comando acima?
